### ISSUE TITLE
SP Method Invoke does not match SP Method Signature 

### ISSUE THREAD

**Issue by tcchrist** [migaman/prefSQL#10]
The script **01_Install_Assembly.sql** create the SP **SP_MultipleSkylineBNL** with four parameters, but the current implementation of the parser only creates 3 parameter to invoke the method:

Parameter **@NumberOfRecords** is missing (guess).

**Comment by migaman** [comment]
I can't reproduce this issue. The current script **01_Install_Assembly.sql** as well as the current method in the class  **prefSQL.SQLSkyline.SP_MultipleSkylineBNL** have 4 parameters.
