### ISSUE TITLE
Algorithms failing...

### ISSUE THREAD

**Issue by mhandschuh** [migaman/prefSQL#11]
The following query executed with the the various algorithms procuce invalid query:
         SELECT TOP 5 
         c.id AS ID, c.title AS Name, c.Price, co.Name_EN AS Color, b.Name_EN AS Body, c.reference 
         FROM Cars_small c 
         LEFT OUTER JOIN colors co ON c.color_id = co.ID 
         LEFT OUTER JOIN bodies b ON c.body_id = b.ID SKYLINE OF c.price LOW, co.name ('rot' >> OTHERS EQUAL), b.name ('Bus' >> 'Kleinwagen') ORDER BY BEST_RANK()

Message: Fehler in SP_SkylineBNL: Incorrect syntax near the keyword 'SELECT'.

**Comment by migaman** [comment]
Works like a charm on my end:-) 
Do you use the "parsePreferenceSQL" or "parseAndExecutePrefSQL" function?

If "parseAndExecutePrefSQL" works fine it has to do with the CLR Installation on your SQL Server. Execute the "01_Install_Assembmly.sql" in the Documents Folder.
