### ISSUE TITLE
Disfavour-Operator does the opposite

### ISSUE THREAD

**Issue by tcchrist** [migaman/prefSQL#32]
It seems that the disfavour-operator does exactly the same as the favour-operator. Maybe somewhere in the code a negation is missing...

Examples:
 - [http://testbed-beta.d3s.ch/?preset=SkylineFavour#]
 - [http://testbed-beta.d3s.ch/?preset=SkylineDisfavour#]

**Comment by migaman** [comment]
Thanks for reporting this bug. There was a  missing negative multiplication
