### ISSUE TITLE
IS MOR IMPORTANT THAN Feature has no effect

### ISSUE THREAD

**Issue by Bulld0zzer** [migaman/prefSQL#40]
Consider the query:
`SELECT c.Id, c.Consumption, c.Price FROM cars c SKYLINE OF c.Consumption LOW IS MORE IMPORTANT THAN c.Price HIGH`

The result will be the same as if executed:
`SELECT c.Id, c.Consumption, c.Price FROM cars c SKYLINE OF c.Consumption LOW`

**Comment by migaman** [comment]
The function is wrongly implemented since a refcatoring (SQLVisitor.VisitSkylineMoreImportant). I will fix it.
