### ISSUE TITLE
Order function WeightedSum not cultural independend

### ISSUE THREAD

**Issue by Bulld0zzer** [migaman/prefSQL#43]
Query tested:
SELECT * FROM cars t1 ORDER BY WEIGHTEDSUM( t1.price LOW 0.5, t1.mileage LOW 0.3, t1.horsepower HIGH 0.2)

Results in:
SELECT * FROM cars t1 ORDER BY (**0,5** * (((t1.price - 300.0) / 697700.0) )) + (**0,3** * (((t1.mileage - 0.0) / 1530000.0) )) + (**0,2** * (((t1.horsepower * -1 - -777.0) / 737.0) ))

I use Microsoft's standard decimal delimiter for Switzerland: ','

**Comment by migaman** [comment]
Can reproduce this. This has to do with the new SP for the ranking functions. I will fix it.
