### ISSUE TITLE
SUM_RANK returns an order other than expected

### ISSUE THREAD

**Issue by Bulld0zzer** [migaman/prefSQL#44]
**Test Setup**
_DATA_
Name = "FIAT"    , Price = 18790  , Color = "pink"
Name = "PORSCHE" , Price = 600000 , Color = "black"
Name = "RUF"     , Price = 698000 , Color = "silver"
Name = "OTHER", Price = 300, Color = "silver"

_QUERY:_
SELECT c.Title as Name, c.Price, co.Name As Color  FROM Cars c LEFT OUTER JOIN Colors co ON c.Color_Id = co.Id 
           SKYLINE OF c.Price HIGH, co.Name ('pink' >> 'black' >> OTHERS EQUAL) 
           ORDER BY SUM_RANK()

**Calculations**
Name = "FIAT"    , Norm_Price = 0.97 , Norm_Color = 0.0 , SUM_RANK = 0.97
Name = "PORSCHE" , Norm_Price = 0.14 , Norm_Color = 0.5 , SUM_RANK = 0.64
Name = "RUF"     , Norm_Price = 0.00 , Norm_Color = 1.0 , SUM_RANK = 1.00
Name = "OTHER", Norm_Price = 1.00, Norm_Color = 1.0, SUM_RANK = 2.00

Therefore, I expect the following order:
1. PORSCHE
2. FIAT
3. RUF

**Returned Order**
1. FIAT
2. PORSCHE
3. RUF

**Comment by tcchrist** [comment]
The sorting function SUM_RANK does not operate with normalized values, as these calculations suggest. 
The cars FIAT, PORSCHE and RUF all have a sum rank of 4 in this example. (1,3), (2,2), (1,3). 
The new sorting function that we are going to implement, will operate with normalized value and result in the expected order.

**Comment by Bulld0zzer** [comment]
Thanks! Then everything make sense!
