### ISSUE TITLE
DISFAVOUR-Operator does not work

### ISSUE THREAD

**Issue by Bulld0zzer** [migaman/prefSQL#45]
**Test Setup**
_DATA_
Name = "FIAT"    , Price = 18790  , Color = "pink"
Name = "PORSCHE" , Price = 600000 , Color = "black"
Name = "RUF"     , Price = 698000 , Color = "silver"
Name = "OTHER", Price = 300, Color = "silver"

_QUERY:_
SELECT c.Title as Name, c.Price, co.Name As Color  FROM Cars c LEFT OUTER JOIN Colors co ON c.Color_Id = co.Id 
           SKYLINE OF c.Price HIGH, co.Name DISFAVOUR 'silver'

_EXPECTED SKYLINE_
1. PORSCHE
2. RUF

**Returned**
1. RUF

 **Related error**
The Query:
_SELECT c.Title as Name, c.Price, co.Name As Color  FROM Cars c LEFT OUTER JOIN Colors co ON c.Color_Id = co.Id 
           SKYLINE OF c.Price HIGH, co.Name ( OTHERS EQUAL >> 'silver' )_
returns the same as
_SELECT c.Title as Name, c.Price, co.Name As Color  FROM Cars c LEFT OUTER JOIN Colors co ON c.Color_Id = co.Id 
           SKYLINE OF c.Price HIGH_

Might be that OTHERS EQUAL does not work if used at the first position.

**Comment by migaman** [comment]
Cannot reproduce this

With this SQL I created your test setup
```
CREATE TABLE cars (
	title varchar(50)
	, price int
	, color_id int
)

CREATE TABLE colors (
	  id int
	, name varchar(50)
)

INSERT INTO colors (id, name) VALUES (1, 'pink')
INSERT INTO colors (id, name) VALUES (2, 'black')
INSERT INTO colors (id, name) VALUES (3, 'silver')

INSERT INTO cars (title, price, color_id) VALUES ('FIAT', 18790, 1)
INSERT INTO cars (title, price, color_id) VALUES ('PORSCHE', 600000, 2)
INSERT INTO cars (title, price, color_id) VALUES ('RUF', 698000, 3)
INSERT INTO cars (title, price, color_id) VALUES ('OTHER', 300, 3)

```

This following SQL result in your data
```
SELECT 
	  title
	, price
	, co.Name 
FROM cars c
LEFT OUTER JOIN colors co ON c.Color_Id = co.Id
```
![data](https://cloud.githubusercontent.com/assets/8789752/18226271/7661dc4a-7206-11e6-8651-e51b6cc6e6c7.png)


Your query results in the following SP Command (using the BNLSort algorithm)
`EXEC dbo.prefSQL_SkylineBNLSortLevel 'SELECT  CAST(c.Price * -1 AS bigint) AS SkylineAttribute0, CAST(CASE WHEN co.Name = ''silver'' THEN 1 ELSE 2 END * -1 AS BIGINT) AS SkylineAttribute1 , c.Title as Name, c.Price, co.Name As Color , CAST(c.Price * -1 AS bigint) AS SkylineAttributec_Price, CAST(CASE WHEN co.Name = ''silver'' THEN 1 ELSE 2 END * -1 AS BIGINT) AS SkylineAttributeco_Name FROM Cars c LEFT OUTER JOIN Colors co ON c.Color_Id = co.Id ORDER BY c.Price * -1, CASE WHEN co.Name = ''silver'' THEN 1 ELSE 2 END * -1', 'LOW;LOW', 0, 0`


And the result is:
![result](https://cloud.githubusercontent.com/assets/8789752/18226295/ea1b981a-7206-11e6-9d94-86fc5abc6f58.png)

**Comment by Bulld0zzer** [comment]
The problem was a typo in the name of the color 'silver'. Therefore the result was correct. My mistake.
I close this issue.
