### ISSUE TITLE
Incorrect statement returned for some Order-functions

### ISSUE THREAD

**Issue by Bulld0zzer** [migaman/prefSQL#47]
**Test-Query:**
`SELECT t1.id FROM cars_small t1 SKYLINE OF t1.price LOW ORDER BY t1.price ASC `

**Test-Code:**
```
SQLCommon common = new SQLCommon
{
        SkylineType = strategy,
        ShowInternalAttributes = true
};
string sqlCommand = common.ParsePreferenceSQL(strPrefSql);
```

**Observations:**
In front of the 'ORDER BY' keyword a white space character is needed for strategies:
- SkylineBNL

returned: `EXEC dbo.prefSQL_SkylineBNLLevel 'SELECT  CAST(t1.price AS bigint) AS SkylineAttribute0 , t1.id , CAST(t1.price AS bigint) AS SkylineAttributet1_price FROM cars_small t1ORDER BY t1.price ASC ', 'LOW', 0, 5`
- SkylineDQ

returned: `EXEC dbo.prefSQL_SkylineDQ 'SELECT  CAST(t1.price AS bigint) AS SkylineAttribute0 , t1.id , CAST(t1.price AS bigint) AS SkylineAttributet1_price FROM cars_small t1ORDER BY t1.price ASC ', 'LOW', 0, 5`

**Comment by migaman** [comment]
I can reproduce it and will fix it. Thanks for reporting
