### ISSUE TITLE
Internal attributes naming: add table identifier to the name

### ISSUE THREAD

**Issue by Bulld0zzer** [migaman/prefSQL#48]
With the change RANKING OF to WEIGHTEDSUM the naming of the internal attributes were changed too.
Before, the table identifier was part of the name. Example:
For RANKING OF-Part: RANKING OF co.Name ('pink' >> 'black' >> OTHERS EQUAL) 0.4, bo.Name ('compact car' >> 'coupé' >> OTHERS EQUAL) 0.6
the internal attributes were named as follows:
- Normalisedco_Name
- Normalisedbo_Name

With the new version the attributes are named like this:
- Ranking_Name
- Ranking_Name1

I prefer the earlier version since it contains all necessary information to identify the attributes. With the new version I have to pay attention to the order(?) of the SKYLINE OF/ WEIGHTESUM preferences.

**Comment by migaman** [comment]
OK, it makes sense to have the full column name (tablename + columnname). I will fix this.

The internal Skyline attributes have the prefix "SkylineAttribute", i.e. SkylineAttributet__price.
Therefore the new names will have the prefix "RankingAttribute", i.e. RankingAttributeco_Name
