### ISSUE TITLE
Concatenation of constant and attribute values result in error

### ISSUE THREAD

**Issue by Bulld0zzer** [migaman/prefSQL#49]
We have some query which concat the imagename and a constant value (url). This results in  the error:

> Incorrect syntax near ''.
> Incorrect syntax near 'ABS'.
> Incorrect syntax near 'ABS'.

**Query:**
`SELECT c.id as id, c.title as name, 'Constant ' + c.reference + as Test FROM cars as c ORDER BY WEIGHTEDSUM(c.price around 1 1.0)`

**parsed query:**
`EXEC dbo.prefSQL_Ranking ' SELECT c.id as id, c.title as name, ''''Constant '''' + c.reference + as Test FROM cars as c ORDER BY WEIGHTEDSUM(c.price around 1 1.0) ', 'SELECT MIN(ABS(c.price - 1)), MAX(ABS(c.price - 1)) FROM cars c', 0, '1', 'ABS(c.price - 1)', True, 'price'`

The number of apostrophes are wrong.

**Comment by migaman** [comment]
Your testing query cannot work (+ before the as keyword).
But I see your point about constants in the sql query. I will fix this

**Comment by Bulld0zzer** [comment]
Thanks for remark. I shortened the query and missed to delete the '+'.
