### ISSUE TITLE
Multiple Skyline not working with Algorithm NativeSQL

### ISSUE THREAD

**Issue by tcchrist** [migaman/prefSQL#5]
The multiple skyline mode is not working for the following scenario. Problems:
 - The column **level** which contains the skyline level is no longer present in the generated query
 - The skyline-attributes-columns which contain the internal value for a preference attribute are no longer present in the generated query

How to reproduce:
```c#
var common = new SQLCommon();
common.SkylineType = SQLCommon.Algorithm.NativeSQL;
common.SkylineUpToLevel = 5;
common.ShowSkylineAttributes = true;
return common.parsePreferenceSQL("SELECT C.Id, C.Price, C.Horsepower FROM cars C SKYLINE OF C.Price LOW");
```

Results:
```sql
SELECT C.Id, C.Price, C.Horsepower  FROM cars C WHERE NOT EXISTS(SELECT C_INNER.Id, C_INNER.Price, C_INNER.Horsepower  FROM cars C_INNER WHERE C_INNER.Price <= C.Price AND ( C_INNER.Price < C.Price) ) 
```

**Comment by migaman** [comment]
The multiple Skyline does not work for the nativeSQL algorithm. This works only with the "MultipleBNL" algorithm. 
The attribute from the Skyline (price) is not shown, because there is only one preference. I just fixed this.
