### ISSUE TITLE
User defined functions not working

### ISSUE THREAD

**Issue by Bulld0zzer** [migaman/prefSQL#52]
**Function definition**
```sql
IF OBJECT_ID (N'dbo.aTest', N'FN') IS NOT NULL  
    DROP FUNCTION aTest;  
GO  
CREATE FUNCTION dbo.aTest
 ( @a float, @b float)  
RETURNS float   
AS   
-- Returns the stock level for the product.  
BEGIN  
    RETURN (@a + @b);  
END;
GO
```

**Query**
```sql
SELECT 
     o.OBJ_ID as Id, 
     dbo.aTest(1.0,2.0) AS Test 
FROM T_Objekt o  
SKYLINE OF  o.OBJ_OBJEKTART ('Haus' >> OTHERS EQUAL)
```

**Exception message**
Error at line 1 no viable alternative at input '1.0'

**Comment by tcchrist** [comment]
some findings:
The parsing of queries containing UDF expression in SELECT or ORDER BY clause works fine.
However, there is a bug but it only occurs provided that:
 * prefSQL is operating in native mode (SkylineType is  SkylineSQL)
 * the schema name does end with the chosen table alias ('dbo' and 'o')

In this case, the parser will replace the schema name with the alias of the inner table.

**Comment by tcchrist** [comment]
bug occurs in this line:
prefSQL.SQLParser.SQLCriterion.120:
```cs
strPreSQL = strPreSQL.Replace(table.Value + ".", table.Value + "_INNER.");
```

suggested bug fix:
replace the line with
```cs
strPreSQL = Regex.Replace(strPreSQL,  @"\b" + table.Value + ".", table.Value + "_INNER.", RegexOptions.IgnoreCase)
```

It's just my first though. Needs further testing and investigation.

**Comment by migaman** [comment]
Already fixed from @tcchrist
