### ISSUE TITLE
WHERE with alphanumeric condition does not work

### ISSUE THREAD

**Issue by Bulld0zzer** [migaman/prefSQL#54]
Steps to reproduce bug:
1. load this [query](http://testbed-beta.abiz.ch/?preset=SkylineWithStepFunction) in the testbed.
2. execute (succeeds ) (runs in CLR mode with stored procedures)
3. turn "use Stored Procedures" off.
4. execute (fails  ) (runs in .NET mode)

**In Detail**
If used with Skyline Of operator the following condition-construct will always result in a SqlException (Please note we did not test with the Weighted Sum operator as it will supposably fail too).
```sql
... WHERE attribute = 'MyCondition' ...
```
_**Exception message**_
System.Data.SqlClient.SqlException: Unclosed quotation mark after the character string 'MyCondition'.
Incorrect syntax near 'MyCondition'.

**Comment by migaman** [comment]
I tested this query in the current prefSQL version and it works. I added a new testcase for it (Method TestIssue54 in the IssueTest Project).

**Comment by Bulld0zzer** [comment]
If used with 
```java
SQLCommon common = new SQLCommon();
common.SkylineType = new SkylineSQL();
```
the error does not occur. In testbed the SkylineBNL algorithm is used. It can be reproduced with the following code lines:
```java
var sqlStatement = "SELECT c.Title AS Name, c.Price, c.Horsepower, b.Name As BodyName "
                               +
                               "FROM Cars c                                                                           "
                               +
                               "    LEFT OUTER JOIN Bodies b ON c.Body_Id = b.Id                                      "
                               + 
                               "WHERE b.Name = 'Bus' "
                               +
                               "SKYLINE OF c.Price LOW 1000 EQUAL, c.Horsepower LOW                                  ";

            SQLCommon common = new SQLCommon();
            //common.SkylineType = new SkylineSQL();
            common.SkylineType = new SkylineBNL();
            DataTable dataTable;

           dataTable = common.ParseAndExecutePrefSQL(_database.ConnectionConfig.ConnectionString,
                    _database.ConnectionConfig.ProviderName,
                    sqlStatement); 
```

**Comment by tcchrist** [comment]
does not occur in CLR mode, however when query is processed via "ParseAndExecutePrefSQL" it fails

**Comment by tcchrist** [comment]
problem identified:
In the method `prefSQL.SQLParser.Helper.DetermineParameters` the following line replaces the escaped quotes in the query:
`strQuery = strQuery.Replace("''", "'").Trim('\'');`

Now, if the query happens to end with a quote as in `WHERE b.Name = 'Bus'` the resulting query will look like this:
`" 'WHERE b.Name = ''Bus'''  "`
The replace-command from above will replace the 3 sequenced quotes with only one, instead of two.

Solution: insert a white-space at the end of the query in the methods `GetStoredProcedureCommand`

I'm working on the bug fix. Ready soon.

**Comment by tcchrist** [comment]
I've pushed a bug fix for this issue. IMHO, this issue could be closed now.

**Comment by migaman** [comment]
OK
