### ISSUE TITLE
Skyline Attribute Fields missing in Resultset of MultipleBNL Algorithm

### ISSUE THREAD

**Issue by tcchrist** [migaman/prefSQL#6]
The multiple skyline mode is not working as expected for the following scenario. Problem:
 - The skyline attribute columns which contain the internal value for the preference attributes are present in the generated query, but not in the resultset.

How to reproduce:
```c#
var common = new SQLCommon();
common.SkylineType = SQLCommon.Algorithm.MultipleBNL;
common.SkylineUpToLevel = 3;
common.ShowSkylineAttributes = true;
return common.parsePreferenceSQL("SELECT C.Id, C.Price, C.Horsepower FROM cars C SKYLINE OF C.Price LOW");
```

Generated Query (looks correct):
```sql
EXEC dbo.SP_MultipleSkylineBNL 'SELECT  C.Price AS SkylineAttribute0 , C.Id, C.Price, C.Horsepower  FROM cars C ORDER BY Price ASC', 'LOW', 3
```

Fields of Resultset:
* Id
* Price
* Horsepower
* Level

Skyline Attribute Fields are missing

**Comment by migaman** [comment]
The attribute from the Skyline (price) is not shown, because there is only one preference. In an early stage of the project the Skyline was only calculated with more than one attribute.  I just fixed this and it works now even with one Preference.
